"""Persistence for the OAuth 2.0 Device Authorization Grant (RFC 8628).

Backs a generic delegated-login mechanism: a browserless client requests
an authorization, the user approves it in a browser out-of-band, and the
client polls for a token — no user credential ever passes through the
client. The Slack integration is the first consumer, but nothing here is
Slack-specific — the initiating client identifies itself with a generic
``client_id`` (display + audit only).

Sibling to :class:`omnigent.server.accounts_store.SqlAlchemyAccountStore`
— same database, separate API surface. Modeled on that store's
atomic single-use redemption (``UPDATE … WHERE … + rowcount``) so a
device_code cannot be exchanged twice and a rotated refresh token
cannot be replayed, even under concurrent requests.

Secrets are never stored raw. The ``device_code`` and each
``refresh_token`` are kept only as HMAC-SHA256 digests, so a database
read cannot recover a usable token. Callers hash with
:func:`hash_secret` before lookup.

See ``designs/DEVICE_AUTH.md`` for the full flow and threat model.
"""

from __future__ import annotations

import hashlib
import hmac
from typing import cast

from sqlalchemy import and_, delete, or_, update
from sqlalchemy.engine import CursorResult

from omnigent.db.db_models import SqlDeviceGrant, current_workspace_id
from omnigent.db.enum_codecs import decode_device_grant_status, encode_device_grant_status
from omnigent.db.utils import get_or_create_engine, make_managed_session_maker
from omnigent.entities import DeviceGrant


def hash_secret(secret: str, key: bytes) -> str:
    """Return the HMAC-SHA256 hex digest of a secret.

    Used to hash the ``device_code`` and refresh tokens before they
    touch the database. Keyed with the server's cookie secret so a
    leaked DB alone (without the key) cannot be used to precompute a
    reverse lookup.

    :param secret: The raw secret string.
    :param key: HMAC key — the server's ``cookie_secret``.
    :returns: Hex-encoded HMAC-SHA256 digest (64 chars).
    """
    return hmac.new(key, secret.encode("utf-8"), hashlib.sha256).hexdigest()


def _to_device_grant(row: SqlDeviceGrant) -> DeviceGrant:
    """Convert a :class:`SqlDeviceGrant` row to a domain entity.

    Drops the hashed secrets — they never leave the store.
    """
    return DeviceGrant(
        id=row.id,
        user_code=row.user_code,
        status=decode_device_grant_status(row.status),
        client_id=row.client_id,
        user_id=row.user_id,
        created_at=row.created_at,
        expires_at=row.expires_at,
        approved_at=row.approved_at,
        last_polled_at=row.last_polled_at,
    )


class DeviceGrantStore:
    """SQLAlchemy-backed persistence for device-authorization grants.

    Concrete class (no ABC) — there is exactly one backend today, and a
    Protocol can be extracted later if a second appears. Constructor
    matches the other server stores so wiring in ``create_app`` is
    mechanical.

    :param storage_location: SQLAlchemy database URI. Shares the
        connection pool with the other stores via
        :func:`get_or_create_engine`.
    """

    def __init__(self, storage_location: str) -> None:
        self.storage_location = storage_location
        self._engine = get_or_create_engine(storage_location)
        self._session = make_managed_session_maker(self._engine)

    def create_grant(
        self,
        grant_id: str,
        *,
        device_code_hash: str,
        user_code: str,
        client_id: str | None,
        created_at: int,
        expires_at: int,
    ) -> DeviceGrant:
        """Persist a new ``pending`` grant.

        The ``grant_id`` and ``device_code`` are generated by the
        caller (see :func:`secrets.token_urlsafe`); the store never
        sees the raw device_code, only its digest.

        :param grant_id: Opaque grant id (public — travels in JWTs).
        :param device_code_hash: HMAC digest of the secret device_code.
        :param user_code: Short human-readable verification code.
        :param client_id: RFC 8628 client identifier — a public string
            naming the requesting application (e.g. ``"slack"``); display +
            audit only.
        :param created_at: Unix epoch seconds.
        :param expires_at: Unix epoch seconds the device_code expires.
        :returns: The created :class:`DeviceGrant`.
        """
        with self._session() as session:
            row = SqlDeviceGrant(
                id=grant_id,
                device_code_hash=device_code_hash,
                user_code=user_code,
                status=encode_device_grant_status("pending"),
                client_id=client_id,
                user_id=None,
                refresh_token_hash=None,
                prev_refresh_token_hash=None,
                created_at=created_at,
                expires_at=expires_at,
                approved_at=None,
                last_polled_at=None,
            )
            session.add(row)
            session.flush()
            return _to_device_grant(row)

    def get_by_user_code(self, user_code: str) -> DeviceGrant | None:
        """Look up a grant by its short verification code.

        Used by the browser consent page to show the initiating client
        before the identity approves. Returns ``None`` if unknown.
        """
        with self._session() as session:
            row = (
                session.query(SqlDeviceGrant)
                .filter(
                    SqlDeviceGrant.workspace_id == current_workspace_id(),
                    SqlDeviceGrant.user_code == user_code,
                )
                .one_or_none()
            )
            return _to_device_grant(row) if row is not None else None

    def get_by_id(self, grant_id: str) -> DeviceGrant | None:
        """Look up a grant by its id."""
        with self._session() as session:
            row = session.get(SqlDeviceGrant, (current_workspace_id(), grant_id))
            return _to_device_grant(row) if row is not None else None

    def get_by_refresh_hash(self, refresh_token_hash: str) -> DeviceGrant | None:
        """Look up the grant currently holding this refresh-token digest.

        Only matches a live (``redeemed``) grant — a revoked grant has
        its ``refresh_token_hash`` cleared to ``NULL``, so a revoked
        token never resolves here. Returns ``None`` if unknown.
        """
        with self._session() as session:
            row = (
                session.query(SqlDeviceGrant)
                .filter(
                    SqlDeviceGrant.workspace_id == current_workspace_id(),
                    SqlDeviceGrant.refresh_token_hash == refresh_token_hash,
                )
                .one_or_none()
            )
            return _to_device_grant(row) if row is not None else None

    def approve(
        self,
        grant_id: str,
        *,
        user_id: str,
        now_epoch_seconds: int,
    ) -> DeviceGrant | None:
        """Atomically bind a ``pending`` grant to an approving identity.

        A single ``UPDATE … WHERE status = pending`` + rowcount check
        makes approval race-safe: a concurrent double-submit cannot
        approve twice, and an already-denied/expired grant is left
        untouched. Sets both the approving ``user_id`` and the
        ``approved_at`` timestamp (which starts the grant's absolute
        lifetime clock).

        Approval binds the authenticated browser identity (``user_id``) to
        the grant — that is the only trust decision here. The ``client_id``
        recorded at creation is display + audit context, not an
        authorization key, so nothing re-filters on it.

        Returns the approved grant, or ``None`` if it was not pending
        (unknown, already decided, or expired).
        """
        with self._session() as session:
            result = cast(
                CursorResult[tuple[object]],
                session.execute(
                    update(SqlDeviceGrant)
                    .where(
                        and_(
                            SqlDeviceGrant.workspace_id == current_workspace_id(),
                            SqlDeviceGrant.id == grant_id,
                            SqlDeviceGrant.status == encode_device_grant_status("pending"),
                            SqlDeviceGrant.expires_at > now_epoch_seconds,
                        )
                    )
                    .values(
                        status=encode_device_grant_status("approved"),
                        user_id=user_id,
                        approved_at=now_epoch_seconds,
                    )
                ),
            )
            if result.rowcount == 0:
                return None
            row = session.get(SqlDeviceGrant, (current_workspace_id(), grant_id))
            return _to_device_grant(row) if row is not None else None

    def deny(self, grant_id: str) -> bool:
        """Mark a ``pending`` grant ``denied``. Returns True if it flipped."""
        with self._session() as session:
            result = cast(
                CursorResult[tuple[object]],
                session.execute(
                    update(SqlDeviceGrant)
                    .where(
                        and_(
                            SqlDeviceGrant.workspace_id == current_workspace_id(),
                            SqlDeviceGrant.id == grant_id,
                            SqlDeviceGrant.status == encode_device_grant_status("pending"),
                        )
                    )
                    .values(status=encode_device_grant_status("denied"))
                ),
            )
            return result.rowcount == 1

    def poll_for_token(
        self,
        device_code_hash: str,
        *,
        now_epoch_seconds: int,
        min_interval_seconds: int,
    ) -> tuple[str, DeviceGrant | None]:
        """Resolve a token-poll by device_code digest.

        Enforces the RFC 8628 poll ``interval`` server-side and records
        ``last_polled_at`` so a client polling faster than allowed gets
        ``slow_down``. This is the read side of the flow — it does NOT
        redeem; :meth:`redeem_approved` performs the atomic single-use
        transition once the outcome is ``approved``.

        :returns: ``(outcome, grant)`` where outcome is one of
            ``"not_found"``, ``"expired"``, ``"slow_down"``,
            ``"pending"``, ``"denied"``, ``"approved"``, ``"revoked"``,
            ``"redeemed"``. ``grant`` is the row when found.
        """
        with self._session() as session:
            row = (
                session.query(SqlDeviceGrant)
                .filter(
                    SqlDeviceGrant.workspace_id == current_workspace_id(),
                    SqlDeviceGrant.device_code_hash == device_code_hash,
                )
                .one_or_none()
            )
            if row is None:
                return ("not_found", None)
            # slow_down: reject-and-record before any other outcome so an
            # aggressive poller is throttled regardless of grant state.
            if (
                row.last_polled_at is not None
                and now_epoch_seconds - row.last_polled_at < min_interval_seconds
            ):
                row.last_polled_at = now_epoch_seconds
                grant = _to_device_grant(row)
                return ("slow_down", grant)
            row.last_polled_at = now_epoch_seconds
            grant = _to_device_grant(row)
            status = decode_device_grant_status(row.status)
            if status in ("denied", "revoked", "redeemed"):
                return (status, grant)
            if row.expires_at <= now_epoch_seconds:
                return ("expired", grant)
            if status == "approved":
                return ("approved", grant)
            return ("pending", grant)

    def redeem_approved(
        self,
        grant_id: str,
        *,
        refresh_token_hash: str,
        now_epoch_seconds: int,
    ) -> DeviceGrant | None:
        """Atomically transition ``approved`` → ``redeemed`` and store the
        first refresh-token digest.

        A single ``UPDATE … WHERE status = approved`` + rowcount check
        guarantees the device_code is exchanged for tokens at most once,
        even if the client fires two concurrent polls after approval.

        Returns the redeemed grant, or ``None`` if it was not in the
        ``approved`` state (already redeemed, expired, revoked, …).
        """
        with self._session() as session:
            result = cast(
                CursorResult[tuple[object]],
                session.execute(
                    update(SqlDeviceGrant)
                    .where(
                        and_(
                            SqlDeviceGrant.workspace_id == current_workspace_id(),
                            SqlDeviceGrant.id == grant_id,
                            SqlDeviceGrant.status == encode_device_grant_status("approved"),
                            SqlDeviceGrant.expires_at > now_epoch_seconds,
                        )
                    )
                    .values(
                        status=encode_device_grant_status("redeemed"),
                        refresh_token_hash=refresh_token_hash,
                    )
                ),
            )
            if result.rowcount == 0:
                return None
            row = session.get(SqlDeviceGrant, (current_workspace_id(), grant_id))
            return _to_device_grant(row) if row is not None else None

    def rotate_refresh_token(
        self,
        grant_id: str,
        *,
        expected_hash: str,
        new_hash: str,
        now_epoch_seconds: int,
        max_lifetime_seconds: int,
    ) -> DeviceGrant | None:
        """Atomically rotate the refresh token.

        The ``WHERE refresh_token_hash = expected_hash`` clause is the
        reuse-detection lock: only the holder of the *current* refresh
        token can rotate it. A client presenting an already-rotated
        token will not match (rowcount 0) — the caller looks it up via
        :meth:`get_by_prev_refresh_hash` and, on a hit, revokes the
        grant as a theft signal.

        An absolute-lifetime clause (``approved_at > now - max_lifetime``)
        refuses rotation once the grant is older than
        ``max_lifetime_seconds``, so a delegated grant cannot refresh
        forever — the user must re-consent. This is distinct from reuse:
        the caller only reaches this method when the presented token is the
        current one (``get_by_refresh_hash`` matched), so a ``None`` return
        here means "aged out," not "replayed," and must not revoke.

        The just-superseded token's digest is preserved in
        ``prev_refresh_token_hash`` precisely so that replay can be
        detected. Only a ``redeemed`` (live) grant can rotate; a revoked
        or denied grant will not match.

        Returns the grant with the new token stored, or ``None`` on a
        stale/mismatched/expired token.
        """
        min_approved_at = now_epoch_seconds - max_lifetime_seconds
        with self._session() as session:
            result = cast(
                CursorResult[tuple[object]],
                session.execute(
                    update(SqlDeviceGrant)
                    .where(
                        and_(
                            SqlDeviceGrant.workspace_id == current_workspace_id(),
                            SqlDeviceGrant.id == grant_id,
                            SqlDeviceGrant.status == encode_device_grant_status("redeemed"),
                            SqlDeviceGrant.refresh_token_hash == expected_hash,
                            SqlDeviceGrant.approved_at > min_approved_at,
                        )
                    )
                    .values(refresh_token_hash=new_hash, prev_refresh_token_hash=expected_hash)
                ),
            )
            if result.rowcount == 0:
                return None
            row = session.get(SqlDeviceGrant, (current_workspace_id(), grant_id))
            return _to_device_grant(row) if row is not None else None

    def get_by_prev_refresh_hash(self, refresh_token_hash: str) -> DeviceGrant | None:
        """Look up a live grant whose *previous* refresh token was this one.

        Used for reuse detection: a client presenting an already-rotated
        refresh token matches here (not :meth:`get_by_refresh_hash`),
        signalling that a stale token was replayed — the caller revokes
        the grant. Only matches ``redeemed`` (live) grants; a revoked
        grant clears both hashes. Returns ``None`` if unknown.
        """
        with self._session() as session:
            row = (
                session.query(SqlDeviceGrant)
                .filter(
                    SqlDeviceGrant.workspace_id == current_workspace_id(),
                    SqlDeviceGrant.status == encode_device_grant_status("redeemed"),
                    SqlDeviceGrant.prev_refresh_token_hash == refresh_token_hash,
                )
                .one_or_none()
            )
            return _to_device_grant(row) if row is not None else None

    def revoke(self, grant_id: str) -> bool:
        """Revoke a grant: mark it ``revoked`` and clear its refresh token.

        Idempotent — revoking an already-revoked grant returns False
        (no row transitioned) but leaves it revoked. Backs
        ``/oauth/revoke`` and reuse-detection. Access tokens carrying
        this ``grant_id`` are rejected via the revocation denylist.
        """
        with self._session() as session:
            result = cast(
                CursorResult[tuple[object]],
                session.execute(
                    update(SqlDeviceGrant)
                    .where(
                        and_(
                            SqlDeviceGrant.workspace_id == current_workspace_id(),
                            SqlDeviceGrant.id == grant_id,
                            SqlDeviceGrant.status != encode_device_grant_status("revoked"),
                        )
                    )
                    .values(
                        status=encode_device_grant_status("revoked"),
                        refresh_token_hash=None,
                        prev_refresh_token_hash=None,
                    )
                ),
            )
            return result.rowcount == 1

    def is_revoked(self, grant_id: str) -> bool:
        """Return True if the grant is unknown or revoked.

        Fails closed: a grant_id with no row (purged, wrong server)
        counts as revoked so a token for a vanished grant is rejected.
        Consulted by the auth layer's revocation check for delegated
        access tokens.
        """
        with self._session() as session:
            row = session.get(SqlDeviceGrant, (current_workspace_id(), grant_id))
            if row is None:
                return True
            return decode_device_grant_status(row.status) == "revoked"

    def purge_expired(
        self, now_epoch_seconds: int, *, max_lifetime_seconds: int | None = None
    ) -> int:
        """Delete grants that can no longer yield a usable token.

        Two housekeeping buckets:

        - ``pending`` / ``denied`` rows whose ``device_code`` window has
          passed (``expires_at <= now``) — they can never be redeemed.
        - When ``max_lifetime_seconds`` is given, ``redeemed`` / ``revoked``
          rows older than that absolute lifetime — their refresh tokens are
          already refused by :meth:`rotate_refresh_token`, so the rows are
          dead weight.

        A live ``redeemed`` grant (within its lifetime) is always kept.
        Returns rows deleted.
        """
        conds = [
            and_(
                SqlDeviceGrant.expires_at <= now_epoch_seconds,
                SqlDeviceGrant.status.in_(
                    [
                        encode_device_grant_status("pending"),
                        encode_device_grant_status("denied"),
                    ]
                ),
            )
        ]
        if max_lifetime_seconds is not None:
            cutoff = now_epoch_seconds - max_lifetime_seconds
            conds.append(
                and_(
                    SqlDeviceGrant.status.in_(
                        [
                            encode_device_grant_status("redeemed"),
                            encode_device_grant_status("revoked"),
                        ]
                    ),
                    SqlDeviceGrant.approved_at.isnot(None),
                    SqlDeviceGrant.approved_at <= cutoff,
                )
            )
        with self._session() as session:
            result = cast(
                CursorResult[tuple[object]],
                session.execute(
                    delete(SqlDeviceGrant).where(
                        and_(
                            SqlDeviceGrant.workspace_id == current_workspace_id(),
                            or_(*conds),
                        )
                    )
                ),
            )
            return result.rowcount
